### ISSUE TITLE
zsh - unknown file attribute

### ISSUE THREAD

**Issue by chrillebile** [Usbac/quich#1]
When doing for example:
`$> quich 5+3*(-2)`
you get:
`zsh: unknown file attribute: 2`

or

`$> quich 13+11+cos(12)`
you get:
`zsh: unknown file attribute: 1`

But more normal commands like work just fine:
```
$> quich 1+1
2
$>
```

**Comment by Usbac** [comment]
@chrillebile  Some characters like the asterisk and parentheses can interfere with zsh and bash in this cases, this can be fixed easily with just putting the operation between quotes :) Like this: $> quich "5+3*(-2)"
