### ISSUE TITLE
wrong answer when I put two minus signs

### ISSUE THREAD

**Issue by ha2san** [Usbac/quich#14]
Hi 
when I put "3--2" as input I receive a bad answer
example :
```
$ ./quich "3--2" -vvv
Tokens > '3' '-' '-' '2' 
Posfix > 3 - 2 - 
Result > -5
```
expected output: 5 or warning

**Comment by Usbac** [comment]
Thank you! It has been fixed and some additional tests were added. 😃

6ec38a92461536d11a2c837a6cfd1076e3220583

**Comment by Usbac** [comment]
Thank you! It has been fixed and some additional tests were added. 😃

6ec38a92461536d11a2c837a6cfd1076e3220583
